name: Deploy to Firebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  deployments: write

concurrency:
  group: firebase-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (Firebase CLI needs ≥20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json

      - name: Install Functions dependencies
        run: |
          cd functions
          npm ci

      - name: Build Functions
        run: |
          cd functions
          npm run build

      - name: Validate Firebase configuration
        run: |
          test -f firebase.json
          test -f public/index.html
          test -f firestore.rules
          test -f storage.rules

  deploy-preview:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy Hosting Preview (PR channel)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIDA_TEA }}
          projectId: vida-tea
          channelId: pr-${{ github.event.number }}   # REQUIRED for previews
          expires: 7d

  # Optional: previews for non-main branch pushes (not PRs)
  # Uncomment this job if you want a preview for any branch push.
  # deploy-branch-preview:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref != 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #     - name: Deploy Hosting Preview (branch)
  #       uses: FirebaseExtended/action-hosting-deploy@v0
  #       with:
  #         repoToken: ${{ secrets.GITHUB_TOKEN }}
  #         firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIDA_TEA }}
  #         projectId: vida-tea
  #         channelId: preview-${{ github.sha }}     # unique per commit
  #         expires: 7d

  deploy-production:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://vida-tea.web.app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIDA_TEA }}
          projectId: vida-tea
          # If you later define a hosting target alias in .firebaserc, add:
          # target: <alias>

      # Ensure Functions deps/build in this job too (separate runner)
      - name: Install Functions dependencies
        run: |
          cd functions
          npm ci

      - name: Build Functions
        run: |
          cd functions
          npm run build

      - name: Deploy Cloud Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project vida-tea
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIDA_TEA }}


